# -*- mode:python -*-

# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# Copyright (c) 2012 ARM Limited
# All rights reserved.
# Authors: Matteo Andreozzi

Import('*')

# Only build the traffic generator if we have support for protobuf as the
# tracing relies on it
if env['HAVE_PROTOBUF']:
    SimObject('ProfileGen.py')
    SimObject('ATPDevice.py')
    Source('profile_gen.cc')
    Source('atp_device.cc')
    DebugFlag('ATP')
