# -*- mode:python -*-

# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# Copyright (c) 2012, 2021 ARM Limited
# All rights reserved.
# Authors: Matteo Andreozzi
#          Adrian Herrera

Import('*')

# Only build if we have protobuf support
if env['CONF']['HAVE_PROTOBUF']:
	ProtoBuf('tp_config.proto')
	ProtoBuf('tp_packet.proto')
	ProtoBuf('tp_stats.proto')

